### ISSUE TITLE
TPAC breakout session on Privacy

### ISSUE THREAD

**Issue by lbdvt** [w3c/web-advertising#128]
Hi,

I think we should have a TPAC breakout session on Privacy.
 
This is a topic of importance, with many active discussions in this group and others. 
 
@AramZS, @jwrosewell, TheMaskMaker, people from the Web Privacy Principles Task Force (@wseltzer) , and others; you are involved in Privacy definition discussions. TPAC is a great opportunity to exchange and communicate on that topic.
 
We could have a session where various viewpoints are presented. Would some of you be interested to participate as speakers in that session?

**Comment by jwrosewell** [comment]
I think that's a great idea.

I'd be happy to talk about the discrimination associated with third and first party definitions and how damaging that is to people's digital privacy in practice.

**Comment by benjaminsavage** [comment]
I’d be happy to discuss my personal viewpoint, which is that “Contextual Integrity” provides a useful framework we can use to guide us.

**Comment by peligio** [comment]
Whose vision of privacy are we all supposed to be building towards? 

I'd like to see some viewpoints presented on what privacy is (maybe some key privacy principles from various viewpoints). It would be particularly valuable to see some of this presented with some insights or evidence (i.e. data), particularly where it reflects actual user viewpoints on privacy. Thanks!

**Comment by darobin** [comment]
Before scheduling a session, we should be clear that it stands a chance of being valuable — knowing that we would have 30min.

For instance, I agree with @benjaminsavage that CI is a powerful framework with which to understand privacy and why establishing different contexts is key, but it's a whole area of research on its own. Helen's original paper has [2k citations](https://scholar.google.com/scholar?cites=9350695840146257775&as_sdt=5,31&sciodt=0,31&hl=en) and the book [another 3k](https://scholar.google.com/scholar?cites=1825191898539175942&as_sdt=5,31&sciodt=0,31&hl=en). There's a whole conference around CI (Privaci, which incidentally was last week). I train people on the basics of using it, and that's already 30min.

I don't want to discourage people picking up CI — on the contrary! — but then I would suggest making the session just about that. It'll be tight but we might be able to cover useful ground, whereas if everything is thrown in at once there's no chance we'll get to anything useful much. For folks who wonder what using CI in practice looks like, I've relied on it to explain privacy in clear terms in [Smashing](https://www.smashingmagazine.com/2021/08/against-privacy-infringement-web/) and before that on [Times Open](https://open.nytimes.com/how-the-new-york-times-thinks-about-your-privacy-bc07d2171531).

If there ends up being a session on privacy other than focused on CI, I would strongly encourage to define it so as to focus on the research and not on someone's random self-serving made-up position. As [discussed elsewhere](https://berjon.com/privacy-reality-check/), we've been exceedingly patient with people who talk about privacy as if it hadn't been an area of active work for decades. There's no need to subject the community to more of that.

**Comment by Jay-PC** [comment]
From the Privacy Co-op perspective, we focus on two pieces of paper: 1) a member's agreement that permits an authorized agency to represent a person's information rights (opt-in/opt-out), 2) an affiliate's agreement where a business agrees to honor those elections in a license based on their own legal privacy policy. Which of those perspectives (data subject or business monetizing data) would this audience be most interested in understanding better, and we would be happy to present. For example, we could talk about the proposed CNS platform in W3C and how it solves problems for either of those parties. Cheers! =Jay

**Comment by darobin** [comment]
@dialtone CI distinguishes between privacy and privacy _norms_. It's an effective framework the break down the components that define a privacy context so that you can ask questions about the norms that you want to apply (specific to that context) in order for the processing to be appropriate. The value is in the definition of privacy, not in the norms which have to be included separately — but made explicit.

You could use CI to define a completely dystopian world in which the norm is that everyone is monitored permanently in all contexts. That norm might suck but CI can define the privacy context correctly. Note that the idea that monitoring can — in a given CI context — be _required_ in order for an information flow to be appropriate is not far-fetched: think for instance of the presence of a lawyer during a police interrogation or of the public record being made of parliamentarian debates. CI can describe and interrogate these, it's the kind of thing that makes it powerful where naive approaches like "privacy is secrecy" or "if there's consent, anything goes" always fall flat on their face.

The idea is that you can define a context with sufficient details that you can ask useful questions about specific aspects. Under what conditions is it fair to share identifiers across contexts knowing that it has been shown to present significant risk and that people do not understand the risk (including those in charge of such systems)? Is the context defined by company ownership? (That's an easy one.) Is that type of processing consentable? Etc.

You mention enforcement by browsers. That is the right thing to do where it is possible and taking into account the fact that browsers should err on the side of safety. However, I think that we still benefit from describing principles even in cases where browsers cannot enforce — because we can find other ways of enforcing them.

To give an example, there is an incipient project amongst news publishers to define what privacy means in a news-reading context (using CI). This could easily be stricter than the privacy model that the Web is moving towards since it would likely include aspects like retention time or limits on profile inferences. I would expect that this can be made binding in various jurisdictions. From my point of view of ensuring our readers have the kind of trustworthy experience that reading the news requires, if the browsers could enforce everything that would be the easiest, but there is still value in defining contextual norms that browsers can't enforce.

**Comment by darobin** [comment]
I agree that surprise is a useful heuristic in thinking about CI and can be used to develop a sense of norms, but we should be conscious of its limits. Some to consider:

* Some surprises are good surprises, and those aren't inappropriate.
* Some actors are unsurprising when they act badly with data, and that's still a privacy violation. 
* It shouldn't be used to offload privacy labour to the user ("you wouldn't be surprised if you'd read the privacy policy, if you'd paid attention to the consent pop-up").
* Privacy harms are often time-shifted. If you give away your whole online behaviour to get "more relevant ads," you might not be surprised to get great cigarette ads today but you might be surprised to not get great insurance ads tomorrow.
