### ISSUE TITLE
public recording for weekly calls

### ISSUE THREAD

**Issue by ablanchard1138** [w3c/web-advertising#72]
Hello, 

We all welcomed the fact the minutes of the weekly call are now publicly available. However, due to many factors (poor sound quality, people talking at the same time or really fast, non-American accents - pardon our french :)), the minutes are sadly often incomplete and fail to convey some crucial points that would be needed to continue fruitful discussions either during following calls or on github. 

I feel the only way to solve this is to record the sessions and make them publicly available.

**Comment by brodrigu** [comment]
I would add that recording the meetings would also make the content more accessible to those who might find the meeting time inconvenient due to timezone offset.

**Comment by wseltzer** [comment]
I invite participants to help scribe and to share corrections to the minutes.

**Comment by ablanchard1138** [comment]
That would be a first step. But I think this is too much work and require to much memory during one hour - one cannot participate actively and transcribe what he said to the letter, which in some cases is important. And sometimes we could argue on 'you said that', 'no I said this', etc.

**Comment by joshuakoran** [comment]
+1 on also making recordings public as we look to improve the written summary notes of the dialog


[http://mailsig.zetaglobal.com/zetasig.png]<https://zetaglobal.com/>

Joshua Koran
Head of Zeta Innovation Labs

e.  jkoran@zetaglobal.com<mailto:jkoran@zetaglobal.com> m. (650) 274-1041

a. San Francisco, CA
www.zetaglobal.com<http://www.zetaglobal.com>
[http://mailsig.zetaglobal.com/linkedin.png]<https://www.linkedin.com/company/zetaglobal>     [http://mailsig.zetaglobal.com/instagram.png] <https://www.instagram.com/zetaglobal>      [http://mailsig.zetaglobal.com/facebook.png] <https://www.facebook.com/zetaglobal>      [http://mailsig.zetaglobal.com/twitter.png] <https://www.twitter.com/zetaglobal>



This message contains information which may be confidential and privileged. You may not use, copy, or disclose to anyone, the message, or any information contained in this message for purposes not intended by the sender. If you have received the message in error, please advise the sender by reply e-mail, and delete the message .

**Comment by hober** [comment]
FWIW, I'm opposed to recording our calls. Recording of calls stifles participation, especially from members of marginalized communities.

**Comment by the-littleidiot** [comment]
definitely +1 on public recordings!

**Comment by jwrosewell** [comment]
@hober Many participants are fearful of saying something that might damage their careers, company share price, or just make them look silly as they don't know all the details. This is true across all forums of the W3C.

Just like public minutes, public recordings also increase this anxiety. However given we agreed to public minutes for this group, better minutes make sense. If recordings help achieve that then I'm for it. One possibility might be to record the meeting and then send the recording to a transcription company to write up the minutes and publish this text.

**Comment by wseltzer** [comment]
I indicated in [email](https://lists.w3.org/Archives/Public/public-web-adv/2020Jul/0032.html) that "W3C practice is to make a record of meetings by the scribed minutes, and not to record meetings if any participant objects." Seeing objections both here and in off-list email, I don't think we should make audio recordings. 

I want all participants to feel comfortable speaking up and participating in a conversation, not an inquisition. The technical issues are difficult enough - let's not add anxiety to the challenges.

**Comment by smenzer** [comment]
I'm indifferent on public recordings, but I think the public meeting minutes should be understandable and complete for those who didn't attend

**Comment by ablanchard1138** [comment]
my goal is to have actionnable transcripts and make these meetings useful - for everyone. The attendees, but also the people living in other timezone, or that don't have the time or resources to attend at this particular hour. The english speakers, but also the people who speaks with non-american accents: French, Italian, Polish... And I hope at some point Japanese, Chinese, or Nigerian. Let's face it: the transcripts do not make justice - at all! - to some of us participations. 

Here is an example that I picked [here](https://www.w3.org/2020/07/21-web-adv-minutes.html), i hope that @BasileLeparmentier won't be upset I picked him:

> Bleparmentier: Across multiple browsers, or across multiple browsers?
> ... in two years, no third party cookies
> ... can Google do cross-site advertising
> ... whereas we will be working with...
> ... no privacy available
> ... are you going to do @
> ... while all of us work with cohort

I think we can all agree that this does not make any sense. I attended the meeting, and I can assure you that this is not what he said. 

And sometimes, complete sentences are missing. Here is one from me (taken from [here](https://www.w3.org/2020/06/23-web-adv-minutes.html))

> arnaud_b_: we need a way to certify the improvements to web advertising
> ... important to gather criteria
> ... and be able to describe why we support a proposal

A full sentence is missing at the beginning. I said "This group is called IWA BG, Improve Web Advertising Business Group, and we need to make sure that we have a way to improve web advertising and do not crush its business". One could argue that the transcript get the general idea. I beg to differ. My goal was to say that indeed we need a way to certify improvements to web advertising, but also that it is actually the mere purpose of this group: the goal is in the name. If we don't agree to what has been and how it has been improved, we have failed as a group.

I also think that as we could all suggest edits to what we say - given that we have the time and resource to have someone taking extensive notes of what we said (in a better fashion than a professional scribe - difficult!) as we say it, and the time to review the full transcript in 7 days. Also, how can we make sure that the transcript does not change the meaning of what was already meant (and transcribed)? Even more difficult to arbitrate: a person could disagree with the transcription of another person's intervention. The only way to achieve exhaustivity and fairness among participant is for the scribe to have access to a recording. Participant could still require edits or removal, that could be mentioned in the document ('removed at the demand of a participant', 'edited for clarity'). 

@hober mentioned that recording does stifle participations, especially in marginalized communities. My goal is definitely not to do that - to the contrary: I want to attract a broader, more diverse participation, from all around the world, with different level of understanding of the language and the technics. A recording (or at least an exhaustive transcript of said recording) will help that. 

My colleagues and I invest a lot of our time in this working group and the privacy discussions in general. These topics are very important for us for many reasons: it impacts the future of our company and of our jobs, sure, but also the whole Web ecosystem, i.e., everything. This might seem grandiloquent but I'm convinced of it. So we want to make sure that the time invested by everyone during these meetings is useful.

**Comment by jwrosewell** [comment]
@ablanchard1138 A very really well made explanation. In summary - if the meeting is worth having, and it is because many paid substantial fees and dedicate substantial time, it's worth recording properly.

Minutes are a general propblem across the W3C. As a new member starting to attend more meetings I'm reading previous meeting minutes in this form to get up to speed and it is hard to work out exactly what was meant.

Also it's not fair on meeting chairs to be expected to run the meeting, particularly ones with a large number of attendeees, and also at the same time record the meeting and contribute to it. It seems like it is time to settle this issues which is [recorded here](https://github.com/w3c/w3process/issues/334) and has been debated for 9 months.

**Comment by wseltzer** [comment]
I appreciate the considerations on both sides. Since I asked whether there were objections to recording and heard multiple objections, I'm going to close this issue.

**Comment by the-littleidiot** [comment]
@wseltzer It is surprising how promptly this issue has been closed. "_...there were objections..._" - Is there any chance to know who objected, for what reasons and why objections have not been published here? 
When it was question to make IWABG minutes public, it was a sort of "+1" vote process via the email thread. The reason of this going public was unclear (but I might have missed some information about it). Anyway, it has resulted in IWABG minutes going public as it has reached a group majority I suppose. Which is a good thing!

As @ablanchard1138 brilliantly exposed, having IWABG minutes public does not make any sense if the way how they are transcribed to the public is not accurate and/or understandable. If the point to make minutes public was truly to give access to a wider range of public around the world, recordings seem to be the more accessible and accurate media we can use to achieve this goal. 

Writting down real-time minutes is a very tough task. It requires a lot of work and focus, specially with different accents from non-native english speakers and/or with some passionate speakers' speech rate and technical terms. There is no doubt that all IWABG members are grateful of the work done here, and so do I. 
However, by keeping minutes in such format, it sounds more like faking an openness of the group and the debates that take place there to a wider audience while the minutes are in fact indigestible for the vast majority of people. I'm afraid we are missing the main purpose that led to the minutes going public here.

As @jwrosewell mentioned, it would give more space to the chairs to focus on leading the debates:
"_Also it's not fair on meeting chairs to be expected to run the meeting, particularly ones with a large number of attendees, and also at the same time record the meeting and contribute to it._".

If some people said something on record they'd like to change, withdraw or comment further, we can image a series of speakers and/or chairs notes attached to the recordings to allow such kind of modifications (specifying speaker name, company and time in the recordings where it the statement as been done). 

We are all here to improve web advertising - _which is pretty much definying the future of the web considering how the web is funded_ - that will result in a better web that preserves user privacy. Because it is a mission whose stakes are so high for millions of businesses and billions of people around the world, it seems necessary that the debates and the decision-making process of the group deserve to be transcribed and communicated in a good manner.

**Comment by jwrosewell** [comment]
Folks commenting on this issue will be interested in [this proposed amendment](https://github.com/w3c/web-advertising/issues/72) to around the recording of meetings. Past commentators might be interested in expressing a view on W3C Process proposal to confirm it meets the concerns expressed here, or where they would like to see it amended. My requirement is to ensure accurate records of meetings.
